---
abstract: 'Simplified pure perl parser for XML'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Parsepp
provides:
  XML::Parsepp:
    file: lib/XML/Parsepp.pm
    version: 0.01
  XML::Parsepp::ExpatNB:
    file: lib/XML/Parsepp.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
